version: "3.8"

services:
  app:
    build:
      context: .
      args:
        APP_ROOT: /var/app
    command: python manage.py runserver ${PORT}
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - ${PORT}:${PORT}
