version: "3.8"

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
  app:
    build:
      context: .
      args:
        APP_ROOT: /var/app
    command: python manage.py runserver 0.0.0.0:${PORT}
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./boltstream:/var/app/boltstream
    depends_on:
      - mysql
